# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-15 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('course_instructor_name', models.CharField(max_length=50)),
                ('course_credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Courses_timings',
            fields=[
                ('course_num', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('timings', models.TimeField(verbose_name='Timings of the course')),
            ],
        ),
        migrations.AddField(
            model_name='courses_info',
            name='course_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.Courses_timings'),
        ),
    ]
