# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-15 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_auto_20180415_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses_info',
            name='id',
        ),
        migrations.AlterField(
            model_name='courses_info',
            name='course_num',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
